apiVersion: automationScript/v1
kind: automationScript
node: go-static-analysis
executor: v1
entry: check.sh
platforms: [darwin, linux]
requirements:
  executables: [sh, go]
toolOutputs:
  - path: packages.txt
    required: true
  - path: vet.json
    required: true
  - path: go-version.txt
    required: true
  - path: go-env.txt
    required: true
resultAdapter: go-static-analysis/v1
