package builtins

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/Jayj1997/gum-workflows/internal/artifact"
	"github.com/Jayj1997/gum-workflows/internal/node"
	"github.com/Jayj1997/gum-workflows/internal/node/scriptnode"
	"github.com/Jayj1997/gum-workflows/internal/project"
)

func TestComplexityBundleRunsEmbeddedAnalyzer(t *testing.T) {
	if runtime.GOOS != "darwin" && runtime.GOOS != "linux" {
		t.Skip("complexity v1 supports Darwin and Linux")
	}
	t.Setenv("GOCACHE", t.TempDir())
	t.Setenv("GOMODCACHE", t.TempDir())
	t.Setenv("GOTOOLCHAIN", "local")
	tests := []struct {
		name      string
		files     map[string]string
		config    node.Config
		verdict   scriptnode.Verdict
		functions int
		maximum   int
	}{
		{name: "multiple functions and threshold finding", files: map[string]string{
			"go.mod":       "module example.com/complexity\n\ngo 1.25.0\n",
			"app.go":       "package app\n\nfunc Small() {}\n\nfunc Large(a, b bool) { if a && b { for a { break } } }\n",
			"app_test.go":  "package app\nfunc ComplexTest(a, b bool) { if a && b { for a { break } } }\n",
			"generated.go": strings.Repeat("// license\n", 15) + "// Code generated by fixture. DO NOT EDIT.\npackage app\nfunc Generated(a, b bool) { if a && b { for a { break } } }\n",
		}, config: node.Config{"maximumCyclomaticComplexity": 3}, verdict: scriptnode.VerdictFailed, functions: 2, maximum: 4},
		{name: "no functions", files: map[string]string{
			"go.mod": "module example.com/empty\n\ngo 1.25.0\n", "doc.go": "package empty\n",
		}, verdict: scriptnode.VerdictNotApplicable},
		{name: "syntax error is business failure", files: map[string]string{
			"go.mod": "module example.com/broken\n\ngo 1.25.0\n", "broken.go": "package broken\nfunc Broken( {\n",
		}, verdict: scriptnode.VerdictFailed},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			workspace := t.TempDir()
			for name, body := range tt.files {
				writeBuiltinFixture(t, filepath.Join(workspace, name), body)
			}
			nodeRunDir := t.TempDir()
			store := artifact.NewMemStore()
			diagnostics := &node.RunDiagnostics{}
			check, err := (complexityExecutor{}).Create(tt.config)
			if err != nil {
				t.Fatal(err)
			}
			outputs, err := check.Execute(node.ExecutionContext{
				Context: context.Background(), Project: project.Context{Workspace: workspace}, Store: store,
				Run: node.RunContext{LogsDir: filepath.Join(nodeRunDir, "logs"), ToolOutputDir: filepath.Join(nodeRunDir, "tool-output")}, Diagnostics: diagnostics,
			}, map[string]artifact.ArtifactRef{"code": {ID: "code", Kind: artifact.KindSourceCode, Version: "1", URI: workspace}})
			if err != nil {
				t.Fatalf("Execute() unexpected error: %v", err)
			}
			body, err := store.Get(outputs["result"])
			if err != nil {
				t.Fatal(err)
			}
			result := body.Data.(scriptnode.ComplexityResult)
			if result.Verdict != tt.verdict {
				t.Fatalf("result = %+v, want %s", result, tt.verdict)
			}
			if tt.functions > 0 && (complexityMetricValue(result.Metrics.FunctionsAnalyzed) != tt.functions || complexityMetricValue(result.Metrics.MaxCyclomaticComplexity) != tt.maximum) {
				t.Fatalf("metrics = %+v", result.Metrics)
			}
			stdout, _ := os.ReadFile(filepath.Join(nodeRunDir, "logs", "stdout.log"))
			if !strings.Contains(string(stdout), "running go cyclomatic complexity check") {
				t.Errorf("stdout = %q", stdout)
			}
			if diagnostics.BundleDigest != complexityBundleDigest || diagnostics.ResultAdapter != complexityAdapterID || diagnostics.Toolchain == nil || diagnostics.Toolchain.Tool != "go ast" {
				t.Errorf("diagnostics = %+v", diagnostics)
			}
			if _, err := os.Stat(filepath.Join(nodeRunDir, "tool-output")); !os.IsNotExist(err) {
				t.Errorf("tool-output remains: %v", err)
			}
			for name := range tt.files {
				if _, err := os.Stat(filepath.Join(workspace, name)); err != nil {
					t.Errorf("workspace input %s changed: %v", name, err)
				}
			}
		})
	}
}

func complexityMetricValue(metric scriptnode.ComplexityMetric) int {
	if metric.Value == nil {
		return -1
	}
	return *metric.Value
}

func TestComplexityConfigDefaultsAndRejectsInvalidValues(t *testing.T) {
	policy, err := complexityPolicy(nil)
	if err != nil || policy.MaximumCyclomaticComplexity != 15 || policy.IncludeTests || !policy.ExcludeGeneratedFiles {
		t.Fatalf("default policy = %+v, error %v", policy, err)
	}
	for _, config := range []node.Config{
		{"maximumCyclomaticComplexity": int64(15)},
		{"maximumCyclomaticComplexity": -1},
		{"includeTests": 1},
		{"excludeGeneratedFiles": "true"},
		{"vendor": true},
	} {
		if _, err := (complexityExecutor{}).Create(config); err == nil {
			t.Errorf("Create(%v) = nil error, want rejection", config)
		}
	}
}
